#!/bin/sh


if [ "$(uname -o)" = "Android" ]; then
  yadm config local.os Android
  echo "Set os to Android"
fi

if [ -d "$HOME/.termux" ]; then
  yadm config --add local.class Termux
  echo "Added Termux class"
fi
