PROTON_ENABLE_WAYLAND=1
# Breaks EAC in Proton
# PROTON_USE_WOW64=1
# NTSync has networking issues (should be resolved by now)
# PROTON_NO_NTSYNC=1
# Fixes rendering
WINE_D3D_CONFIG="renderer=vulkan"
# winhttp.dll=n,b;version.dll=n,b - Enables modding
# winepulse.drv=d - Disables PulseAudio driver to use ALSA
WINEDLLOVERRIDES="winhttp.dll=n,b;version.dll=n,b;winepulse.drv=d;winealsa.drv=b"
# Configure ALSA audio https://www.reddit.com/r/linux_gaming/comments/1pt63sb/
# WINEALSA_SPATIAL=1
# WINEALSA_CHANNELS=2
# Disables console spam
WINEDEBUG=err-all,fixme-all
