# ============ Fallbacks
XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-${HOME}/.local/state}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-${HOME}/.cache}

# ============ GENERAL
_SILENT_JAVA_OPTIONS="-Djava.util.prefs.userRoot='${XDG_CONFIG_HOME}/java' -Djavafx.cachedir='${XDG_CACHE_HOME}/openjfx'"

# ============ DATA: ~/.local/share
CARGO_HOME="${XDG_DATA_HOME}/cargo"
GNUPGHOME="${XDG_DATA_HOME}/gnupg"
DOTNET_CLI_HOME="${XDG_DATA_HOME}/dotnet"
WINEPREFIX="${XDG_DATA_HOME}/wine"
GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
GOPATH="${XDG_DATA_HOME}/go"
PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"
PYTHONUSERBASE="${XDG_DATA_HOME}/python"
RENPY_PATH_TO_SAVES="${XDG_DATA_HOME}/renpy"
RENPY_MULTIPERSISTENT="${XDG_DATA_HOME}/renpy_shared"
MINIKUBE_HOME="${XDG_DATA_HOME}/minikube"

# ============ STATE: ~/.local/state
PYTHON_HISTORY="${XDG_STATE_HOME}/python_history"

# ============ CONFIG: ~/.config
GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"
WGETRC="${XDG_CONFIG_HOME}/wgetrc"
KUBECONFIG="${XDG_CONFIG_HOME}/kube"

# ============ CACHE: ~/.cache
PYTHONPYCACHEPREFIX="${XDG_CACHE_HOME}/python"
NUGET_PACKAGES="${XDG_CACHE_HOME}/NuGetPackages"
MESA_SHADER_CACHE_DIR="${XDG_CACHE_HOME}/mesa_shader_cache_db"
MESA_GLSL_CACHE_DIR="${XDG_CACHE_HOME}/mesa_shader_cache_db"
CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
__GL_SHADER_DISK_CACHE_PATH="${XDG_CACHE_HOME}/nv"
GIT_CACHE_PATH="${XDG_CACHE_HOME}/git"
KUBECACHEDIR="${XDG_CACHE_HOME}/kube"

